$do_cd = 1;
$pdf_mode = 1;
$out_dir = "build";
$aux_dir = "build";
$bibtex_use = 1;
$interaction = "nonstopmode";
$recorder = 1;
$pdflatex = 'pdflatex -shell-escape -interaction=nonstopmode -halt-on-error -file-line-error -synctex=1 %O %S';
